security:
  sessions: NEVER
spring:
  session:
    store-type: redis
logging:
  level:
    org.springframework:
      security: DEBUG
      session: TRACE


#spring.cloud.config.uri=http://localhost:8000
